name: Bump and release
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
                    
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        skip-version-file: 'true'
        skip-on-empty: 'true'
        skip-commit: 'false'
    
    - name: Write version.txt file
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      shell: bash
      run: echo ${{ steps.changelog.outputs.tag }} > version.txt
      
    - name: Update version.txt file
      uses: test-room-7/action-update-file@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      with:
        file-path: version.txt
        commit-msg: Bump version.txt and CHANGELOG.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}

    - name: Update channel notification
      uses: Sniddl/discord-commits@v1.3
      with:
        webhook: ${{ secrets.UPDATES_WEBHOOK }}
        embed: '{ "title": "Mini Scripts: {{ commit.title }}", "description": "{{ commit.description }}"}'
        last-commit-only: false